# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://www.conferenciadesafiobrasil.com.br/"
title: Conferência Desafio Brasil
email: labfgv@gmail.com
author: Laboratório de Políticas Públicas da FGV
description: > # "Write an awesome description for your new site here. 
  A Conferência Desafio Brasil discute o desenvolvimento do Brasil.
copyright: 'Copyright &copy; 2016 <a href="http://www.labfgv.com/">Lab FGV</a>.'
credits: 'Créditos: Landing Page by <a href="http://startbootstrap.com/">Start Bootstrap</a>; <a href="https://pages.github.com/">GitHub Pages</a>; <a href="https://jekyllrb.com/">Jekyll</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#         social          #
# ----------------------- #

social:
  - title: facebook
    url: https://m.facebook.com/conferenciadesafiobrasil/
  - title: envelope
    url: mailto:labfgv@gmail.com?subject=[contato] conferência desafio brasil

# ----------------------- #
#         members         #
# ----------------------- #

people:
- name: José Mendonça Bezerra Filho
  pic: 1.png
  minibio: Ministro da Educação
  mesa: educacao
  gt: nao
  social:
    - title: file-text-o
      url: portal.mec.gov.br/gabinete-do-ministro
    - title: facebook
      url: https://pt-br.facebook.com/mendoncafilhoPE/ 
- name: Lígia Stocche Barbosa
  pic: ligia.png
  minibio: Engenheira de formação, mas ao longo da vida migrou para a educação. É fundadora e membro do conselho deliberativo do Movimento Mapa Educação e trabalha na Fundação Lemann.
  gt: nao
  mesa: educacao
  social:
    - title: file-text-o
      url: http://www.mapaeducacao.com/quemsomos.html
# ----------------------- #
#          apoio          #
# ----------------------- #

parceiros:
- parceiro: Instituto República
  logo: republica.png
  url: http://www.institutorepublica.edu.ar/
- parceiro: Instituto Publix
  logo: publix.png
  url: http://www.institutopublix.com.br/
- parceiro: Mapa Educação
  logo: mapa.png
  url: http://www.mapaeducacao.com/
- parceiro: FGV Social
  logo: fgv-social.png
  url: http://cps.fgv.br/
 - parceiro: CIEB
    logo: cieb.png
    url: www.cieb.net.br/
  - parceiro: PENSA
    logo: pensa.png
    url: http://pensa.rio/main/pensa/
