# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://labfgv.github.io
title: Conferência Desafio Brasil
email: labfgv@gmail.com
author: Laboratório de Políticas Públicas da FGV
description: > # "Write an awesome description for your new site here. 
  A Conferência Desafio Brasil discute o desenvolvimento do Brasil.
copyright: 'Copyright &copy; 2016 labFGV.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: inscreva-se
    url: http://www.fgv.br/eventos/?P_EVENTO=2990&P_IDIOMA=0
